services:
  web:
    build:
      context: .
    command: sh -c "make run"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.dev
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - django_network

  migrate:
    profiles: ["migrate"]
    build:
      context: .
    entrypoint: ["/entrypoint.migrate.sh"]
    volumes:
      - .:/app
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.dev
    depends_on:
      db:
        condition: service_started
    networks:
      - django_network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-parkme_db}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - django_network

  redis:
    image: redis:7-alpine
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network:
    driver: bridge
